name: Game Pass Notifier

on:
  schedule:
    - cron: '0 0,6,12 * * *'  # 매일 09:00, 15:00, 21:00 KST
  workflow_dispatch:  # 수동 실행 허용

permissions:
  contents: write  # seen_articles.json 쓰기 권한

jobs:
  check-gamepass:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests beautifulsoup4

      - name: Run Game Pass Notifier
        run: python gamepass_notifier.py
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}

      - name: Commit and push seen_articles.json
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add seen_articles.json
          git diff --staged --quiet || git commit -m "업데이트: 확인한 기사 목록 갱신 [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
